"""Deterministic failure → Jira issue mapping (build bible §19 S7.4).

S7.4: "failure + S4.1 diagnosis (category, root_cause, evidence,
confidence) → issue create-or-update". :func:`build_issue_payload` is the
single deterministic producer of the Jira ``fields`` body — it is LLM-free
(pure input → output, same input always yields the same payload), so it can
be pinned by the golden set (``golden/jira_v1.json`` ``mappings`` section)
and exercised by the API job, the CLI (``map`` subcommand), and the fake
server tests from one place.

The mapping is intentionally conservative and stable:

- ``summary`` — ``[QA] <category>[: <root_cause>]`` (root cause trimmed),
  capped at Jira's 255-character summary limit;
- ``description`` — Atlassian Document Format (ADF): a Diagnosis section
  (category / confidence / root cause), a Failure section (test name,
  run, status, error excerpt, up to ``MAX_EVIDENCE`` evidence lines,
  suggested fix when present), and a provenance footer;
- ``labels`` — ``qa-copilot`` + ``failure-<category>`` (stable filtering).

:class:`JiraMappingError` (a ``ValueError``) is raised for input that
cannot be mapped (invalid project key, non-string failure pieces) — fail
loud, never guess (§15: never invent facts; the failure data is the ground
truth).
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any

from qa_copilot_integrations.jira.client import validate_project_key

#: Jira caps summary at 255 characters.
MAX_SUMMARY = 255
#: Cap on evidence lines carried into the issue (keeps the body compact).
MAX_EVIDENCE = 5
#: Excerpt cap for the raw error text in the description.
MAX_ERROR_EXCERPT = 800
#: Issue type — S7.4 links *failures*, and a "Bug" is the right type.
ISSUE_TYPE_NAME = "Bug"
#: Stable labels (filtering in Jira dashboards).
BASE_LABEL = "qa-copilot"
LABEL_PREFIX = "failure-"
#: Provenance footer (no timestamps: re-link updates must stay
#: deterministic and idempotent for the same input).
FOOTER = "Generated by AI QA Copilot (S7.4 Jira linking, deterministic mapping)."


class JiraMappingError(ValueError):
    """The failure/diagnosis input cannot be mapped to a valid Jira issue."""


def _clean(value: object, field: str) -> str | None:
    """Normalize a failure/diagnosis piece to stripped text (or None)."""
    if value is None or (isinstance(value, str) and not value.strip()):
        return None
    if not isinstance(value, str):
        raise JiraMappingError(f"{field} must be a string, got {type(value).__name__}")
    return value.strip()


def _truncate(value: str, limit: int) -> str:
    if len(value) <= limit:
        return value
    return value[: max(0, limit - 1)].rstrip() + "…"


def _paragraph(text: str) -> dict[str, Any]:
    """One ADF paragraph."""
    return {"type": "paragraph", "content": [{"type": "text", "text": text}]}


def _heading(text: str) -> dict[str, Any]:
    """One ADF heading (level 2)."""
    return {
        "type": "heading",
        "attrs": {"level": 2},
        "content": [{"type": "text", "text": text}],
    }


def _list(items: Sequence[str]) -> dict[str, Any]:
    """One ADF bullet list (items already capped by the caller)."""
    return {
        "type": "list",
        "attrs": {"ordered": False, "start": 1},
        "content": [{"type": "listItem", "content": [_paragraph(item)]} for item in items],
    }


def build_summary(category: str | None, root_cause: str | None) -> str:
    """``[QA] <category>[: <root_cause>]`` — ≤ 255 chars (golden-pinned)."""
    category_text = (category or "unknown").strip() or "unknown"
    summary = f"[QA] {category_text}"
    rc = root_cause.strip() if isinstance(root_cause, str) else None
    if rc:
        budget = MAX_SUMMARY - len(summary) - 2  # ": "
        if budget > 10:
            summary = f"{summary}: {_truncate(rc, budget)}"
    summary = summary[:MAX_SUMMARY]
    if not summary:
        raise JiraMappingError("summary is empty")
    return summary


def build_description(
    *,
    failure_id: str | None,
    test_name: str | None,
    run_id: str | None,
    status: str | None,
    error: str | None,
    category: str | None,
    confidence: float | None,
    root_cause: str | None,
    evidence: Sequence[str] | None,
    suggested_fix: str | None,
) -> dict[str, Any]:
    """ADF description body (deterministic; golden-pinned)."""
    if confidence is not None and not (0.0 <= float(confidence) <= 1.0):
        raise JiraMappingError(f"confidence must be in [0, 1], got {confidence!r}")
    category_text = (category or "unknown").strip() or "unknown"
    content: list[dict[str, Any]] = []

    # -- Diagnosis (S4.1) ---------------------------------------------------
    content.append(_heading("Diagnosis"))
    content.append(_paragraph(f"Category: {category_text}"))
    confidence_text = str(confidence) if confidence is not None else "n/a"
    content.append(_paragraph(f"Confidence: {confidence_text}"))
    if root_cause and isinstance(root_cause, str) and root_cause.strip():
        content.append(_paragraph(f"Root cause: {root_cause.strip()}"))

    # -- Failure (S3) -------------------------------------------------------
    content.append(_heading("Failure"))
    facts: list[str] = []
    if failure_id:
        facts.append(f"Failure id: {failure_id}")
    if test_name and isinstance(test_name, str) and test_name.strip():
        facts.append(f"Test: {test_name.strip()}")
    if run_id:
        facts.append(f"Run: {run_id}")
    if status and isinstance(status, str) and status.strip():
        facts.append(f"Status: {status.strip()}")
    content.extend(_paragraph(f) for f in facts)
    if error and isinstance(error, str) and error.strip():
        content.append(_heading("Error"))
        content.append(_paragraph(_truncate(error.strip(), MAX_ERROR_EXCERPT)))
    evidence_items = [
        item.strip() for item in (evidence or []) if isinstance(item, str) and item.strip()
    ][:MAX_EVIDENCE]
    if evidence_items:
        content.append(_heading("Evidence"))
        content.append(_list(evidence_items))
    if suggested_fix and isinstance(suggested_fix, str) and suggested_fix.strip():
        content.append(_heading("Suggested fix (needs human approval)"))
        content.append(_paragraph(suggested_fix.strip()))

    content.append(_paragraph(FOOTER))
    return {"type": "doc", "version": 1, "content": content}


def build_issue_payload(
    failure: Mapping[str, Any],
    project_key: str,
) -> dict[str, Any]:
    """Map one S3/S4.1 failure record to a Jira ``fields`` body.

    ``failure`` keys (all optional): ``id``, ``test_name``, ``run_id``,
    ``status``, ``error``, ``category``, ``confidence``, ``root_cause``,
    ``evidence`` (list of strings), ``suggested_fix``.
    ``project_key`` is required and validated (fail loud, §15).
    """
    validate_project_key(project_key)  # raises ValueError on bad input
    category = _clean(failure.get("category"), "failure.category")
    root_cause = _clean(failure.get("root_cause"), "failure.root_cause")
    confidence = failure.get("confidence")
    if confidence is not None and not isinstance(confidence, (int, float)):
        raise JiraMappingError(
            f"failure.confidence must be a number, got {type(confidence).__name__}"
        )
    evidence = failure.get("evidence")
    if evidence is not None and not isinstance(evidence, (list, tuple)):
        raise JiraMappingError(
            f"failure.evidence must be a list of strings, got {type(evidence).__name__}"
        )
    return {
        "project": {"key": project_key},
        "issuetype": {"name": ISSUE_TYPE_NAME},
        "summary": build_summary(category, root_cause),
        "description": build_description(
            failure_id=_clean(failure.get("id"), "failure.id"),
            test_name=_clean(failure.get("test_name"), "failure.test_name"),
            run_id=_clean(failure.get("run_id"), "failure.run_id"),
            status=_clean(failure.get("status"), "failure.status"),
            error=_clean(failure.get("error"), "failure.error"),
            category=category,
            confidence=confidence,
            root_cause=root_cause,
            evidence=evidence,
            suggested_fix=_clean(failure.get("suggested_fix"), "failure.suggested_fix"),
        ),
        "labels": [BASE_LABEL, f"{LABEL_PREFIX}{(category or 'unknown').strip() or 'unknown'}"],
    }


__all__ = [
    "BASE_LABEL",
    "FOOTER",
    "ISSUE_TYPE_NAME",
    "LABEL_PREFIX",
    "MAX_ERROR_EXCERPT",
    "MAX_EVIDENCE",
    "MAX_SUMMARY",
    "JiraMappingError",
    "build_description",
    "build_issue_payload",
    "build_summary",
]
