"""LLM-backed agents. S1.1 Requirement, S1.2 Test Design, S2.3 Automation,
S4.1 Investigator, S5.4 Knowledge Q&A, S6.3 Regression Advisor."""

from .automation import (
    AUTOMATOR_NAME,
    FRAMEWORKS,
    LANGUAGES,
    AutomationAgent,
    AutomationAgentResult,
    AutomationInput,
    GeneratedTest,
    parse_generated_test,
)
from .failure_investigator import (
    INVESTIGATOR_NAME,
    Diagnosis,
    FailureInvestigatorAgent,
    FailureInvestigatorAgentResult,
    InvestigatorInput,
    parse_diagnosis,
)
from .fixer import (
    FIXER_NAME,
    FixerAgent,
    FixerAgentResult,
    FixerInput,
    FixProposal,
    parse_fix_proposal,
)
from .knowledge_qa import (
    KNOWLEDGE_QA_NAME,
    KnowledgeContext,
    KnowledgeQAAgent,
    KnowledgeQAAgentResult,
    KnowledgeQAInput,
    QAAnswer,
    QACitation,
    parse_qa_answer,
    render_context,
)
from .regression_advisor import (
    ADVISOR_NAME,
    SUMMARY_SOURCE_LLM,
    SUMMARY_SOURCE_STUB,
    AdvisorInput,
    RegressionAdvisorAgent,
    RegressionAdvisorResult,
    RegressionSummary,
    parse_summary,
    stub_summary,
)
from .requirement import (
    AGENT_NAME,
    SUGGESTED_TEST_TYPES,
    RequirementAgent,
    RequirementAgentResult,
    RequirementAnalysis,
    RequirementInput,
)
from .test_design import (
    PRIORITIES,
    RISK_LEVELS,
    TEST_CASE_TYPES,
    TEST_DESIGNER_NAME,
    TestCase,
    TestDesignAgent,
    TestDesignAgentResult,
    TestDesignInput,
    TestSuite,
)

__all__ = [
    "AGENT_NAME",
    "ADVISOR_NAME",
    "AUTOMATOR_NAME",
    "FIXER_NAME",
    "FRAMEWORKS",
    "INVESTIGATOR_NAME",
    "KNOWLEDGE_QA_NAME",
    "LANGUAGES",
    "PRIORITIES",
    "RISK_LEVELS",
    "SUMMARY_SOURCE_LLM",
    "SUMMARY_SOURCE_STUB",
    "SUGGESTED_TEST_TYPES",
    "TEST_CASE_TYPES",
    "TEST_DESIGNER_NAME",
    "AdvisorInput",
    "AutomationAgent",
    "AutomationAgentResult",
    "AutomationInput",
    "Diagnosis",
    "FailureInvestigatorAgent",
    "FailureInvestigatorAgentResult",
    "FixProposal",
    "FixerAgent",
    "FixerAgentResult",
    "FixerInput",
    "GeneratedTest",
    "InvestigatorInput",
    "KnowledgeContext",
    "KnowledgeQAAgent",
    "KnowledgeQAAgentResult",
    "KnowledgeQAInput",
    "QAAnswer",
    "QACitation",
    "RegressionAdvisorAgent",
    "RegressionAdvisorResult",
    "RegressionSummary",
    "RequirementAgent",
    "RequirementAgentResult",
    "RequirementAnalysis",
    "RequirementInput",
    "TestDesignAgent",
    "TestDesignAgentResult",
    "TestDesignInput",
    "TestCase",
    "TestSuite",
    "parse_diagnosis",
    "parse_fix_proposal",
    "parse_generated_test",
    "parse_qa_answer",
    "parse_summary",
    "render_context",
    "stub_summary",
]
