"""project_members (S0.8 auth baseline)

Revision ID: 2d783f832c48
Revises: 60fa1027d8d2
Create Date: 2026-08-27 09:09:45.837306

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d783f832c48"
down_revision: str | Sequence[str] | None = "60fa1027d8d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # S0.8 auth baseline: dev-user password hash (§31.3) + project-scoped roles.
    op.add_column("users", sa.Column("password_hash", sa.String(length=255), nullable=True))
    op.create_table(
        "project_members",
        sa.Column("project_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column(
            "role",
            sa.Enum("owner", "member", "viewer", name="projectrole", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("project_id", "user_id"),
    )
    op.create_index(
        op.f("ix_project_members_user_id"), "project_members", ["user_id"], unique=False
    )
    # NOTE: autogenerate also detected the pre-existing ``failures_confidence_check``
    # and ``jobs_progress_check`` check constraints as "removed" because the ORM
    # models declared them anonymously. They are kept: the models now name them
    # to match the DB (see ``models.py``), and the drop lines were removed here.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_members_user_id"), table_name="project_members")
    op.drop_table("project_members")
    op.drop_column("users", "password_hash")
    # ### end Alembic commands ###
