"""initial core schema

Revision ID: 60fa1027d8d2
Revises:
Create Date: 2026-08-26 22:21:22.111335

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "60fa1027d8d2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector before creating embeddings(vector). The pgvector/pgvector
    # image ships the extension but it must be enabled per database (§8, S0.5).
    # Idempotent; requires a role with CREATE privilege (the compose `qa`
    # role is the database owner, so this works out of the box).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("plan", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "prompt_versions",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("model_class", sa.String(length=16), nullable=False),
        sa.Column("input_budget", sa.Integer(), nullable=True),
        sa.Column("output_budget", sa.Integer(), nullable=True),
        sa.Column("schema_ref", sa.String(length=128), nullable=True),
        sa.Column("temperature", sa.Double(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version", name="uq_prompt_versions_name_version"),
    )
    op.create_index(op.f("ix_prompt_versions_name"), "prompt_versions", ["name"], unique=False)
    op.create_table(
        "repositories",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("default_branch", sa.String(length=255), nullable=True),
        sa.Column("scan_status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "test_cases",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "functional",
                "negative",
                "boundary",
                "risk",
                "accessibility",
                "security",
                name="testtype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("high", "medium", "low", name="priority", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("preconditions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("steps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expected_results", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "risk",
            sa.Enum("high", "medium", "low", name="risklevel", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "files",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("repository_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(length=64), nullable=True),
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("organization_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("repository_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ai_sessions",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("project_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("task_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_sessions_project_id"), "ai_sessions", ["project_id"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("project_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "requirement_analysis",
                "test_case_generation",
                "automation_generation",
                "run_execution",
                "failure_analysis",
                "fix_proposal",
                "repository_indexing",
                name="jobtype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "completed",
                "failed",
                "cancelled",
                name="jobstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("progress", sa.Double(), nullable=False),
        sa.Column("input_ref", sa.String(length=1024), nullable=True),
        sa.Column("output_ref", sa.String(length=1024), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("progress >= 0.0 AND progress <= 1.0"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_project_id"), "jobs", ["project_id"], unique=False)
    op.create_table(
        "knowledge_documents",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("project_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("source_ref", sa.String(length=1024), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_knowledge_documents_project_id"),
        "knowledge_documents",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "requirements",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("project_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("acceptance_criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "risk",
            sa.Enum("high", "medium", "low", name="risklevel", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_requirements_project_id"), "requirements", ["project_id"], unique=False
    )
    op.create_table(
        "test_runs",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("project_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("commit_sha", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_test_runs_project_id"), "test_runs", ["project_id"], unique=False)
    op.create_table(
        "ai_actions",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("session_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("agent", sa.String(length=64), nullable=False),
        sa.Column("tool", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("input_hash", sa.String(length=128), nullable=True),
        sa.Column("output_ref", sa.String(length=1024), nullable=True),
        sa.Column("approval_status", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["session_id"], ["ai_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_actions_session_id"), "ai_actions", ["session_id"], unique=False)
    op.create_table(
        "embeddings",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("knowledge_document_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("vector", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
        sa.ForeignKeyConstraint(
            ["knowledge_document_id"], ["knowledge_documents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_embeddings_knowledge_document_id"),
        "embeddings",
        ["knowledge_document_id"],
        unique=False,
    )
    op.create_table(
        "requirement_test_cases",
        sa.Column("requirement_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("test_case_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(["requirement_id"], ["requirements.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["test_case_id"], ["test_cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("requirement_id", "test_case_id"),
    )
    op.create_index(
        op.f("ix_requirement_test_cases_test_case_id"),
        "requirement_test_cases",
        ["test_case_id"],
        unique=False,
    )
    op.create_table(
        "test_results",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("run_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("test_case_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("duration", sa.Double(), nullable=True),
        sa.Column("failure_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["test_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_test_results_run_id"), "test_results", ["run_id"], unique=False)
    op.create_index(
        op.f("ix_test_results_test_case_id"), "test_results", ["test_case_id"], unique=False
    )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("test_result_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "trace",
                "screenshot",
                "video",
                "console",
                "network",
                "dom",
                "log",
                name="artifacttype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("uri", sa.String(length=2048), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["test_result_id"], ["test_results.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_artifacts_test_result_id"), "artifacts", ["test_result_id"], unique=False
    )
    op.create_table(
        "failures",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("test_result_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "product_defect",
                "automation_defect",
                "environment_defect",
                "test_data_defect",
                "flaky_behavior",
                "unknown",
                name="failurecategory",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("root_cause", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Double(), nullable=True),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("suggested_fix", sa.Text(), nullable=True),
        sa.Column("needs_human_approval", sa.Boolean(), nullable=False),
        sa.CheckConstraint("confidence IS NULL OR (confidence >= 0.0 AND confidence <= 1.0)"),
        sa.ForeignKeyConstraint(["test_result_id"], ["test_results.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("test_result_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Note: the ``vector`` extension is deliberately NOT dropped here — other
    extensions or databases may still depend on it; dropping it is a manual
    DBA action (``DROP EXTENSION vector;``).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("failures")
    op.drop_index(op.f("ix_artifacts_test_result_id"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(op.f("ix_test_results_test_case_id"), table_name="test_results")
    op.drop_index(op.f("ix_test_results_run_id"), table_name="test_results")
    op.drop_table("test_results")
    op.drop_index(
        op.f("ix_requirement_test_cases_test_case_id"), table_name="requirement_test_cases"
    )
    op.drop_table("requirement_test_cases")
    op.drop_index(op.f("ix_embeddings_knowledge_document_id"), table_name="embeddings")
    op.drop_table("embeddings")
    op.drop_index(op.f("ix_ai_actions_session_id"), table_name="ai_actions")
    op.drop_table("ai_actions")
    op.drop_index(op.f("ix_test_runs_project_id"), table_name="test_runs")
    op.drop_table("test_runs")
    op.drop_index(op.f("ix_requirements_project_id"), table_name="requirements")
    op.drop_table("requirements")
    op.drop_index(op.f("ix_knowledge_documents_project_id"), table_name="knowledge_documents")
    op.drop_table("knowledge_documents")
    op.drop_index(op.f("ix_jobs_project_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_ai_sessions_project_id"), table_name="ai_sessions")
    op.drop_table("ai_sessions")
    op.drop_table("projects")
    op.drop_table("files")
    op.drop_table("users")
    op.drop_table("test_cases")
    op.drop_table("repositories")
    op.drop_index(op.f("ix_prompt_versions_name"), table_name="prompt_versions")
    op.drop_table("prompt_versions")
    op.drop_table("organizations")
    # ### end Alembic commands ###
