"""generated_tests (S2.4 diff review + human approval)

Revision ID: 7e9a4b2c1d3f
Revises: 2d783f832c48
Create Date: 2026-08-28 12:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7e9a4b2c1d3f"
down_revision: str | Sequence[str] | None = "2d783f832c48"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # S2.4: generated-test review (§19 S2.4) — the S2.3 automation agent
    # output as a reviewable row; status is the domain
    # GeneratedTestStatus wire string (pending/approved/applied/rejected).
    op.create_table(
        "generated_tests",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("project_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("job_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("test_case_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("file_path", sa.String(length=512), nullable=False),
        sa.Column("file_path_pattern", sa.String(length=512), nullable=True),
        sa.Column("language", sa.String(length=32), nullable=False),
        sa.Column("framework", sa.String(length=64), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("notes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("repository_path", sa.String(length=2048), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "applied",
                "rejected",
                name="generatedteststatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reviewed_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["test_case_id"], ["test_cases.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_generated_tests_project_id"), "generated_tests", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_generated_tests_project_id"), table_name="generated_tests")
    op.drop_table("generated_tests")
    # ### end Alembic commands ###
